const principles = [
  {
    num: "01",
    title: "Liability Isolation",
    body: "Each subsidiary is a separate legal entity. A liability in one business cannot reach the others. This is the foundational reason the structure works at scale — it lets us take operational risks in each individual company without putting the whole portfolio at risk.",
  },
  {
    num: "02",
    title: "Tax-Efficient Capital Recycling",
    body: "Cash generated by profitable subsidiaries can be deployed into new acquisitions without first passing through a tax event. The holding company is a capital recycling machine — profits from mature businesses fund new acquisitions continuously, compounding without friction.",
  },
  {
    num: "03",
    title: "Shared Services at Scale",
    body: "Accounting, insurance, HR, technology, and compliance can be centralized. A business doing $400K in revenue cannot afford a full-time CFO. But twenty such businesses, operated together, can share one — and each business gets CFO-level discipline at a fraction of the cost.",
  },
  {
    num: "04",
    title: "Exit Optionality",
    body: "Individual subsidiaries can be sold independently. The entire portfolio can be sold to a PE firm at a platform multiple. Or the holding company itself can be taken public. The structure creates multiple exit paths simultaneously, not one.",
  },
];

export default function HoldingCompany101() {
  return (
    <div className="rh-page">
      <div className="rh-label">Renaissance Holdings · 01</div>
      <h1 className="rh-h1">Holding Company 101</h1>
      <p className="rh-subtitle">
        Why the structure matters as much as the strategy.
      </p>

      <p className="rh-body">
        A holding company is a parent entity that owns stakes in one or more operating subsidiaries. It
        doesn't manufacture anything. It doesn't serve customers directly. Its job is to own, allocate
        capital to, and create the conditions under which its subsidiaries can compound.
      </p>

      <p className="rh-body">
        Berkshire Hathaway is the canonical example — but the model works at every scale. The key insight
        is that the holding company structure is not just a legal convenience. It is an{" "}
        <em className="rh-italic">operational architecture</em> that enables outcomes which would be
        impossible for standalone businesses.
      </p>

      <hr className="rh-divider" />

      <div style={{ display: "flex", flexDirection: "column", gap: "36px", marginBottom: "52px" }}>
        {principles.map((p) => (
          <div key={p.num}>
            <div style={{ display: "flex", alignItems: "baseline", gap: "16px", marginBottom: "12px" }}>
              <span style={{
                fontFamily: "system-ui, -apple-system, sans-serif",
                fontSize: "10px", color: "#4A4840", letterSpacing: "0.14em", minWidth: "22px",
              }}>
                {p.num}
              </span>
              <h3 style={{
                fontFamily: "Georgia, 'Times New Roman', serif",
                fontSize: "22px", fontWeight: "600", color: "#E8E4D8", margin: 0,
              }}>
                {p.title}
              </h3>
            </div>
            <p className="rh-body" style={{ marginBottom: 0, paddingLeft: "38px" }}>{p.body}</p>
          </div>
        ))}
      </div>

      <hr className="rh-divider" />

      <p className="rh-body">
        The model we're building is not Berkshire — we're not buying large, established businesses and
        holding them forever. We're buying micro-cap service businesses at 2–3x earnings and assembling
        them into a platform that commands 5–8x on exit. The holding company structure is what makes
        the arbitrage possible.
      </p>

      <div className="rh-callout">
        <p className="rh-callout-text">
          The individual businesses are the raw material. The holding company is the factory that refines them.
        </p>
      </div>
    </div>
  );
}